#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pass
Version  : 1.7.3
Release  : 2
URL      : https://git.zx2c4.com/password-store/snapshot/password-store-1.7.3.tar.xz
Source0  : https://git.zx2c4.com/password-store/snapshot/password-store-1.7.3.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: pass-bin = %{version}-%{release}
Requires: pass-data = %{version}-%{release}
Requires: pass-license = %{version}-%{release}
Requires: pass-man = %{version}-%{release}

%description
======================
Simple Password Store
by Jason Donenfeld
Jason@zx2c4.com
======================

%package bin
Summary: bin components for the pass package.
Group: Binaries
Requires: pass-data = %{version}-%{release}
Requires: pass-license = %{version}-%{release}

%description bin
bin components for the pass package.


%package data
Summary: data components for the pass package.
Group: Data

%description data
data components for the pass package.


%package license
Summary: license components for the pass package.
Group: Default

%description license
license components for the pass package.


%package man
Summary: man components for the pass package.
Group: Default

%description man
man components for the pass package.


%prep
%setup -q -n password-store-1.7.3
cd %{_builddir}/password-store-1.7.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604085138
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1604085138
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pass
cp %{_builddir}/password-store-1.7.3/COPYING %{buildroot}/usr/share/package-licenses/pass/ffe620e004df8ec67f8310673447f712fc0e90c9
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pass

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/pass
/usr/share/zsh/site-functions/_pass

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pass/ffe620e004df8ec67f8310673447f712fc0e90c9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pass.1
